name: ClickTpa
version: '1.6v'
main: com.jklmao.plugin.ClickTpa
api-version: 1.13
authors: [ jklmao ]
description: Simple TPA plugin for Spigot/Paper Software

commands:
  tpa:
    usage: /<command>
    aliases: [teleport]
  tpahere:
    usage: /<command>
  tpaccept:
    usage: /<command>
    aliases: [tpyes]
  tpadeny:
    usage: /<command>
    aliases: [tpdeny, tpno]
  tpo:
    usage: /<command>
    alises: [tp]
  tpohere:
    usage: /<command>
    aliases: [s, tphere]
  tptoggle:
    usage: /<command>
  tpacancel:
    usage: /<command>
    aliases: [tpcancel]
  clicktparl:
    usage: /<command>
    aliases: [ctparl]
